fix : import directory of register page
why ? : caused error during import 'src/App.tsx(8,26): error TS2307:
Cannot find module '@/pages/auth/Registrer' or its corresponding type
declarations.'